### ISSUE TITLE
Build issue of master branch due to "major" and "minor"

### ISSUE THREAD

**Issue by Jazzz42** [Zilliqa/Zilliqa#863]
Unable to build branch master with gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
branch testnetv4-dev can be built without any problems.

This issue is common:
https://github.com/protocolbuffers/protobuf/issues/4654
https://stackoverflow.com/questions/22240973/major-and-minor-macros-defined-in-sys-sysmacros-h-pulled-in-by-iterator

/Zilliqa/build/src/libMessage/ZilliqaMessage.pb.h:3372:13: error: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>. [-Werror]
   ::google::protobuf::uint32 major() const;

**Comment by Gnnng** [comment]
seems duplicate to #853. We will have a fix soon

**Comment by bb111189** [comment]
Fixed and merged to master (https://github.com/Zilliqa/Zilliqa/pull/864)

**Comment by Jazzz42** [comment]
Thanks. I confirm that the master build works ok with gcc 7.3.0
