### ISSUE TITLE
[BUG] Dependencies error when build from source

### ISSUE THREAD

**Issue by evermorn** [Zilliqa/Zilliqa#3606]
### Issue 
When trying to build from source by instruction on the main page I got this type of error:
```
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindLibevent.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Libevent",
  but CMake did not find one.

  Could not find a package configuration file provided by "Libevent" with any
  of the following names:

    LibeventConfig.cmake
    libevent-config.cmake

  Add the installation prefix of "Libevent" to CMAKE_PREFIX_PATH or set
  "Libevent_DIR" to a directory containing one of the above files.  If
  "Libevent" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/build/build/CMakeFiles/CMakeOutput.log".

```

And this is not about Libevent. If you comment Libevent in CMakeList, you got same error for other libs:

```
-- We are on a Linux system
CMake Error at CMakeLists.txt:36 (find_package):
  By not providing "Findbsoncxx.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "bsoncxx", but
  CMake did not find one.

  Could not find a package configuration file provided by "bsoncxx" with any
  of the following names:

    bsoncxxConfig.cmake
    bsoncxx-config.cmake

  Add the installation prefix of "bsoncxx" to CMAKE_PREFIX_PATH or set
  "bsoncxx_DIR" to a directory containing one of the above files.  If
  "bsoncxx" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

```
I think
`git submodule update --init --recursive`
is not working well, because when you run it, nothing happens.

### Steps to Reproduce
Build from source according to instruction on the repo main page.

#### Expected
Build is working well.

#### Actual
Cmake error.

#### Impact:
- [+] Medium

### Additional Details
* Versions: v9.0.1
* Operating System: ubuntu 22.04
* Installed packages: all from build instruction

**Comment by evermorn** [comment]
Ok, found some workaround, but now I got cpp build error:
```
build/build/src -isystem /build/build/vcpkg_installed/x64-linux-dynamic/include -std=c++20 -O2 -ggdb -DNDEBUG -Wall -Werror -pedantic -Wextra -Wno-error=deprecated-declarations -Wno-unused-parameter -std=c++2a -o CMakeFiles/Metrics.dir/Api.cpp.o -c /build/src/libMetrics/Api.cpp
/build/src/libMetrics/Api.cpp:74:1: error: redefinition of 'const char _ZTSZN9SingletonIN3zil7metrics6FilterEE11GetInstanceERKSt8functionIFSt10shared_ptrIS2_EvEEbEd0_UlvE_ []'
   74 | }  // namespace zil
      | ^
/build/src/libMetrics/Api.cpp:74:1: note: 'const char _ZTSZN9SingletonIN3zil7metrics6FilterEE11GetInstanceERKSt8functionIFSt10shared_ptrIS2_EvEEbEd0_UlvE_ [97]' previously defined here
src/libMetrics/CMakeFiles/Metrics.dir/build.make:123: recipe for target 'src/libMetrics/CMakeFiles/Metrics.dir/Api.cpp.o' failed
make[2]: *** [src/libMetrics/CMakeFiles/Metrics.dir/Api.cpp.o] Error 1
make[2]: Leaving directory '/build/build'
CMakeFiles/Makefile2:1923: recipe for target 'src/libMetrics/CMakeFiles/Metrics.dir/all' failed
make[1]: *** [src/libMetrics/CMakeFiles/Metrics.dir/all] Error 2
make[1]: Leaving directory '/build/build'
Makefile:173: recipe for target 'all' failed
make: *** [all] Error 2

```
Can you help with that?

**Comment by evermorn** [comment]
Ok, I found a way and build is finaly succeded. Here is some thoughts that may be helpful to someone.

1) 
Vcpkg is not optional build step. This thing download all dependencies.

2) 
There is requirement in README.md about gcc version: they said that it must be >=11. 
But I tried to build with gcc-11 and get this bug:
```
build/build/src -isystem /build/build/vcpkg_installed/x64-linux-dynamic/include -std=c++20 -O2 -ggdb -DNDEBUG -Wall -Werror -pedantic -Wextra -Wno-error=deprecated-declarations -Wno-unused-parameter -std=c++2a -o CMakeFiles/Metrics.dir/Api.cpp.o -c /build/src/libMetrics/Api.cpp
/build/src/libMetrics/Api.cpp:74:1: error: redefinition of 'const char _ZTSZN9SingletonIN3zil7metrics6FilterEE11GetInstanceERKSt8functionIFSt10shared_ptrIS2_EvEEbEd0_UlvE_ []'
   74 | }  // namespace zil
      | ^
/build/src/libMetrics/Api.cpp:74:1: note: 'const char _ZTSZN9SingletonIN3zil7metrics6FilterEE11GetInstanceERKSt8functionIFSt10shared_ptrIS2_EvEEbEd0_UlvE_ [97]' previously defined here
src/libMetrics/CMakeFiles/Metrics.dir/build.make:123: recipe for target 'src/libMetrics/CMakeFiles/Metrics.dir/Api.cpp.o' failed
make[2]: *** [src/libMetrics/CMakeFiles/Metrics.dir/Api.cpp.o] Error 1
make[2]: Leaving directory '/build/build'
CMakeFiles/Makefile2:1923: recipe for target 'src/libMetrics/CMakeFiles/Metrics.dir/all' failed
make[1]: *** [src/libMetrics/CMakeFiles/Metrics.dir/all] Error 2
make[1]: Leaving directory '/build/build'
Makefile:173: recipe for target 'all' failed
make: *** [all] Error 2

```
Tried to build with gcc-12( it was last version, 12.2.1 ) and get this bug:
```
24% Building CXX object src/libNetwork/CMakeFiles/Network.dir/RumorManager.cpp.o
cd /build/build/src/libNetwork && /usr/bin/c++ -DENABLE_LOGS_PREVIEW -DHAVE_CPP_STDLIB -I/build/src/depends -I/include -I/build/src/depends/cryptoutils/include -I/build/src -I/build/build/src -isystem /build/build/vcpkg_installed/x64-linux-dynamic/include -std=c++20 -O2 -ggdb -DNDEBUG -Wall -Werror -pedantic -Wextra -Wno-error=deprecated-declarations -Wno-unused-parameter -std=c++20 -MD -MT src/libNetwork/CMakeFiles/Network.dir/RumorManager.cpp.o -MF CMakeFiles/Network.dir/RumorManager.cpp.o.d -o CMakeFiles/Network.dir/RumorManager.cpp.o -c /build/src/libNetwork/RumorManager.cpp
In file included from /root/install/gcc-12/include/c++/12.2.1/string:50,
                 from /root/install/gcc-12/include/c++/12.2.1/bits/locale_classes.h:40,
                 from /root/install/gcc-12/include/c++/12.2.1/bits/ios_base.h:41,
                 from /root/install/gcc-12/include/c++/12.2.1/streambuf:41,
                 from /root/install/gcc-12/include/c++/12.2.1/bits/streambuf_iterator.h:35,
                 from /root/install/gcc-12/include/c++/12.2.1/iterator:66,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/operators.hpp:98,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/serialization/strong_typedef.hpp:27,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/serialization/serialization.hpp:14,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/serialization/split_free.hpp:22,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/serialization/nvp.hpp:35,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/bimap/bimap.hpp:57,
                 from /build/build/vcpkg_installed/x64-linux-dynamic/include/boost/bimap.hpp:13,
                 from /build/src/libNetwork/RumorManager.h:21,
                 from /build/src/libNetwork/RumorManager.cpp:18:
In function 'constexpr typename __gnu_cxx::__enable_if<std::__is_byte<_Tp>::__value, void>::__type std::__fill_a1(_Tp*, _Tp*, const _Tp&) [with _Tp = unsigned char]',
    inlined from 'constexpr void std::__fill_a(_FIte, _FIte, const _Tp&) [with _FIte = unsigned char*; _Tp = unsigned char]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_algobase.h:968:21,
    inlined from 'constexpr _OutputIterator std::__fill_n_a(_OutputIterator, _Size, const _Tp&, random_access_iterator_tag) [with _OutputIterator = unsigned char*; _Size = long unsigned int; _Tp = unsigned char]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_algobase.h:1119:20,
    inlined from 'constexpr _OI std::fill_n(_OI, _Size, const _Tp&) [with _OI = unsigned char*; _Size = long unsigned int; _Tp = unsigned char]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_algobase.h:1148:29,
    inlined from 'static constexpr _ForwardIterator std::__uninitialized_default_n_1<true>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator = unsigned char*; _Size = long unsigned int]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_uninitialized.h:663:29,
    inlined from 'static constexpr _ForwardIterator std::__uninitialized_default_n_1<true>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator = unsigned char*; _Size = long unsigned int]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_uninitialized.h:655:9,
    inlined from 'constexpr _ForwardIterator std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator = unsigned char*; _Size = long unsigned int]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_uninitialized.h:701:20,
    inlined from 'constexpr _ForwardIterator std::__uninitialized_default_n_a(_ForwardIterator, _Size, allocator<_Tp>&) [with _ForwardIterator = unsigned char*; _Size = long unsigned int; _Tp = unsigned char]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_uninitialized.h:766:44,
    inlined from 'constexpr void std::vector<_Tp, _Alloc>::_M_default_append(size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]' at /root/install/gcc-12/include/c++/12.2.1/bits/vector.tcc:662:41,
    inlined from 'constexpr void std::vector<_Tp, _Alloc>::resize(size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]' at /root/install/gcc-12/include/c++/12.2.1/bits/stl_vector.h:1011:21,
    inlined from 'static void Serializable::SetNumber(zbytes&, unsigned int, numerictype, unsigned int) [with numerictype = unsigned int]' at /build/src/common/Serializable.h:63:17,
    inlined from 'RumorManager::RawBytes RumorManager::GenerateGossipForwardMessage(const RawBytes&)' at /build/src/libNetwork/RumorManager.cpp:402:36:
/root/install/gcc-12/include/c++/12.2.1/bits/stl_algobase.h:942:25: error: 'void* __builtin_memset(void*, int, long unsigned int)' offset [0, 2] is out of the bounds [0, 0] [-Werror=array-bounds]
  942 |         __builtin_memset(__first, static_cast<unsigned char>(__tmp), __len);
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
src/libNetwork/CMakeFiles/Network.dir/build.make:148: recipe for target 'src/libNetwork/CMakeFiles/Network.dir/RumorManager.cpp.o' failed
make[2]: *** [src/libNetwork/CMakeFiles/Network.dir/RumorManager.cpp.o] Error 1
make[2]: Leaving directory '/build/build'
CMakeFiles/Makefile2:2224: recipe for target 'src/libNetwork/CMakeFiles/Network.dir/all' failed
make[1]: *** [src/libNetwork/CMakeFiles/Network.dir/all] Error 2
make[1]: Leaving directory '/build/build'
Makefile:158: recipe for target 'all' failed
make: *** [all] Error 2

```
I even tried to build with gcc-10 - bugs again:
```
0% Building CXX object src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/RemoteStorageDB.cpp.o
cd /build/build/src/libRemoteStorageDB && /usr/bin/c++  -I/build/src/depends -I/include -I/build/src/depends/cryptoutils/include -I/build/src -isystem /build/build/vcpkg_installed/x64-linux-dynamic/include -std=c++20 -O2 -ggdb -DNDEBUG -Wall -Werror -pedantic -Wextra -Wno-error=deprecated-declarations -Wno-unused-parameter -std=c++2a -MD -MT src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/RemoteStorageDB.cpp.o -MF CMakeFiles/RemoteStorageDB.dir/RemoteStorageDB.cpp.o.d -o CMakeFiles/RemoteStorageDB.dir/RemoteStorageDB.cpp.o -c /build/src/libRemoteStorageDB/RemoteStorageDB.cpp
In file included from /build/src/common/Hashes.h:21,
                 from /build/src/common/TxnStatus.h:21,
                 from /build/src/libRemoteStorageDB/RemoteStorageDB.h:21,
                 from /build/src/libRemoteStorageDB/RemoteStorageDB.cpp:18:
/build/src/depends/common/FixedHash.h: In member function 'size_t dev::FixedHash<N>::hash::operator()(const dev::FixedHash<N>&) const [with unsigned int N = 32; size_t = long unsigned int]':
/build/src/depends/common/FixedHash.h:345:26: error: 'bit_cast' is not a member of 'std'; did you mean 'bad_cast'?
  345 |         auto data = std::bit_cast<std::array<uint64_t, 4>>(value.m_data);
      |                          ^~~~~~~~
      |                          bad_cast
/build/src/depends/common/FixedHash.h:345:57: error: expected primary-expression before '>' token
  345 |         auto data = std::bit_cast<std::array<uint64_t, 4>>(value.m_data);
      |                                                         ^~
src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/build.make:78: recipe for target 'src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/RemoteStorageDB.cpp.o' failed
make[2]: *** [src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/RemoteStorageDB.cpp.o] Error 1
make[2]: Leaving directory '/build/build'
CMakeFiles/Makefile2:2593: recipe for target 'src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/all' failed
make[1]: *** [src/libRemoteStorageDB/CMakeFiles/RemoteStorageDB.dir/all] Error 2
make[1]: Leaving directory '/build/build'
Makefile:158: recipe for target 'all' failed
make: *** [all] Error 2

```
The only version of gcc that is worked for me is 12.1.0. I think it's because of it's exactly version that you can install in ubuntu 22.04 with apt.

3)
Result binaries use about 60 libs, most of them installed by vcpkg. So run zilliqa outside build container is bad idea.
